# -*- coding: utf-8 -*-
"""actormapfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182VfqpYR6_MllR1fMJto5kpuLQAEMltn
"""

#!/usr/bin/env python
import sys
import csv

def parse_gross(gross_str):
    # Remove commas and convert to integer
    if gross_str:
        return int(gross_str.replace(',', ''))
    return None  # Return None if the gross value is missing


for line in sys.stdin:
    try:
        # Read and parse the CSV line
        reader = csv.reader([line])
        for row in reader:
            imdb_rating = float(row[6])  # IMDB_Rating column
            gross_earnings = parse_gross(row[15])  # Gross column

            # Emit key-value pairs for each top-billed actor
            actors = [row[10], row[11], row[12], row[13]]  # Star1 to Star4 columns
            for actor in actors:
                if actor:
                    print(f"{actor}\t{imdb_rating}\t{gross_earnings}")
    except Exception as e:
        continue