# -*- coding: utf-8 -*-
"""map_director.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etf5jnRbJ1lxaVntKRer-wEL7oZvmKVw
"""

#!/usr/bin/env python
import sys
import csv

def parse_gross(gross_str):
    # Remove commas and convert to integer
    if gross_str:
        return int(gross_str.replace(',', ''))
    return None  # Return None if the gross value is missing

for line in sys.stdin:
    try:
        # Read and parse the CSV line
        reader = csv.reader([line])
        for row in reader:
            gross_earnings = parse_gross(row[15])  # Gross column

            # Skip the row if gross earnings are missing or zero
            if gross_earnings is None:
                continue

            director = row[10]  # Director column
            imdb_rating = float(row[6])  # IMDB_Rating column

            # Emit key-value pair
            print(f"{director}\t{imdb_rating}\t{gross_earnings}")
    except Exception as e:
        continue