# -*- coding: utf-8 -*-
"""actorred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJSBbzONXFUedqly9NcS4Moxp-DzInSy
"""

#!/usr/bin/env python
import sys

current_actor = None
total_ratings = 0
total_gross = 0
count = 0

for line in sys.stdin:
    try:
        actor, imdb_rating, gross_earnings = line.strip().split('\t')
        imdb_rating = float(imdb_rating)
        gross_earnings = int(gross_earnings)

        if current_actor == actor:
            total_ratings += imdb_rating
            total_gross += gross_earnings
            count += 1
        else:
            if current_actor:
                avg_rating = total_ratings / count
                avg_gross = total_gross / count
                print(f"{current_actor}\t{avg_rating}\t{avg_gross}")

            current_actor = actor
            total_ratings = imdb_rating
            total_gross = gross_earnings
            count = 1
    except Exception as e:
        continue

# Output the last actor's average
if current_actor:
    avg_rating = total_ratings / count
    avg_gross = total_gross / count
    print(f"{current_actor}\t{avg_rating}\t{avg_gross}")