# -*- coding: utf-8 -*-
"""red0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUiv2tbv3oxol3OktgHEmChZ5xWe8x2k
"""

#!/usr/bin/env python
import sys

current_director = None
total_ratings = 0
total_gross = 0
count = 0

for line in sys.stdin:
    try:
        director, imdb_rating, gross_earnings = line.strip().split('\t')
        imdb_rating = float(imdb_rating)
        gross_earnings = int(gross_earnings)

        if current_director == director:
            total_ratings += imdb_rating
            total_gross += gross_earnings
            count += 1
        else:
            if current_director:
                avg_rating = total_ratings / count
                avg_gross = total_gross / count
                print(f"{current_director}\t{avg_rating}\t{avg_gross}")

            current_director = director
            total_ratings = imdb_rating
            total_gross = gross_earnings
            count = 1
    except Exception as e:
        continue

# Output the last director's average
if current_director:
    avg_rating = total_ratings / count
    avg_gross = total_gross / count
    print(f"{current_director}\t{avg_rating}\t{avg_gross}")